image: openjdk:8-jdk

include:
  - template: Code-Quality.gitlab-ci.yml

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - test
  - ui test

before_script:
  - apt-get update -qq && apt-get install -y -qq maven

cache:
  key: "$CI_JOB_NAME"
  paths:
    - $CI_PROJECT_DIR/.m2/repository

.unit test base:
  stage: test
  variables:
    REPO_URL: http://download.eclipse.org/releases/latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile -Declipse-repo.url=$REPO_URL
    - mvn $MAVEN_CLI_OPTS verify -PUnitTest -Declipse-repo.url=$REPO_URL

Unit Test latest:
  extends: .unit test base

Unit Test 2019-03:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/2019-03

Unit Test 2018-12:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/2018-12

Unit Test 2018-09:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/2018-09

Unit Test Photon:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/photon

Unit Test Oxygen:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/oxygen

Unit Test Neon:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/neon

Unit Test Mars:
  extends: .unit test base
  variables:
    REPO_URL: http://download.eclipse.org/releases/mars

UI Test:
  stage: ui test
  when: manual
  script:
    - apt-get update -qq && apt-get install -y -qq xvfb iceweasel
    - Xvfb :99 -ac &
    - export DISPLAY=:99
    - mvn $MAVEN_CLI_OPTS clean verify -PUITest
