image: openjdk:8-jdk

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

before_script:
  - apt-get update -qq && apt-get install -y -qq maven

cache:
  key: "$CI_JOB_NAME"
  paths:
    - $CI_PROJECT_DIR/.m2/repository

.test job template:
  stage: test
  variables:
    REPO_URL: http://download.eclipse.org/releases/2019-06
  script:
    - apt-get update -qq && apt-get install -y -qq xvfb iceweasel
    - Xvfb :99 -ac &
    - export DISPLAY=:99
    - mvn $MAVEN_CLI_OPTS verify -PTest -Declipse-repo.url=$REPO_URL
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*.xml

.latest eclipse job template:
  variables:
    REPO_URL: http://download.eclipse.org/releases/latest
  allow_failure: true

.unit test job template:
  extends: .test job template
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -PUnitTest

Test and coverage:
  extends: .test job template
  script:
    - apt-get update -qq && apt-get install -y -qq xvfb iceweasel
    - Xvfb :99 -ac &
    - export DISPLAY=:99
    - mvn $MAVEN_CLI_OPTS clean verify -PCoverage
    - cat org.zkovari.eclipse.gitlab.coverage.report/target/site/jacoco-aggregate/index.html

Unit Test JDK 11:
  extends: .test job template
  image: openjdk:11-jdk
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -PUnitTest -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

Test latest:
  extends:
    - .test job template
    - .latest eclipse job template

Test 2019-12:
  extends: .test job template
  allow_failure: true
  variables:
    REPO_URL: http://download.eclipse.org/releases/2019-12

Test 2019-09:
  extends: .test job template
  allow_failure: true
  variables:
    REPO_URL: http://download.eclipse.org/releases/2019-09

Test 2019-03:
  extends: .test job template
  variables:
    REPO_URL: http://download.eclipse.org/releases/2019-03

Test 2018-12:
  extends: .test job template
  variables:
    REPO_URL: http://download.eclipse.org/releases/2018-12

Test 2018-09:
  extends: .test job template
  variables:
    REPO_URL: http://download.eclipse.org/releases/2018-09

Test Photon:
  extends: .test job template
  variables:
    REPO_URL: http://download.eclipse.org/releases/photon

Test Oxygen:
  extends: .test job template
  variables:
    REPO_URL: http://download.eclipse.org/releases/oxygen

Unit Test Neon:
  extends: .unit test job template
  allow_failure: true
  variables:
    REPO_URL: http://download.eclipse.org/releases/neon

Unit Test Mars:
  extends: .unit test job template
  allow_failure: true
  variables:
    REPO_URL: http://download.eclipse.org/releases/mars
