image: openjdk:8-jdk

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

stages:
  - build
  - unit test
  - ui test

before_script:
  - apt-get update -qq && apt-get install -y -qq maven

cache:
  key: "$CI_JOB_NAME"
  paths:
    - $CI_PROJECT_DIR/.m2/repository

.prepare ui test:
  script:
    - apt-get update -qq && apt-get install -y -qq xvfb iceweasel
    - apt-get install  -yqq
    - Xvfb :99 -ac &
    - export DISPLAY=:99

Compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

Unit Test:
  stage: unit test
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -PUnitTest

UI Test:
  extends: .prepare ui test
  stage: ui test
  when: manual
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -PUITest
